project:
  type: website
  output-dir: docs
  resources:
    - assets/**

website:
  title: "Wesley Zheng"
  favicon: "assets/icon.png"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - slides.qmd
      - text: Resume
        href: /assets/resume.pdf
        target: _blank
      - publications.qmd
      - courses.qmd
    right:
      - text: Notes
        href: https://wkaiz.github.io/discussions/
        target: _blank
      - text: Projects
        href: https://wkaiz.github.io/projects/
        target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



